on:
    workflow_dispatch:
name: container

jobs:
  render-website:
    runs-on: ubuntu-latest
    container: rocker/verse:4.1.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download the data
        run: |
          Rscript -e "source('R/download.R')"

      - name: Render the site
        run: |
          R -e "install.packages(c('DT','distill'))"
          Rscript -e "rmarkdown::render_site('website')"

      - name: Commit Result
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add data
          git commit -m 'Add the data' || echo "No changes to commit"
          git add docs
          git commit -m 'Update the website' || echo "No changes to commit"
          git push origin || echo "No changes to commit"